package com.personalticktick.app.domain

import java.time.DayOfWeek
import java.time.LocalDate
import java.time.YearMonth
import java.time.temporal.ChronoUnit
import java.time.temporal.TemporalAdjusters

/** Pure task lifecycle rules. All date boundaries are natural local days. */
object TaskLifecycle {
    fun isOverdue(task: Task, today: LocalDate): Boolean {
        if (task.status != TaskStatus.ACTIVE || task.isProjection) return false
        val dueDate = task.endDate ?: task.startDate ?: return false
        val start = task.startDate
        if (start != null && start in task.repeatRule.excludedDates) return false
        return dueDate.isBefore(today)
    }

    fun isVisibleOn(task: Task, date: LocalDate): Boolean {
        if (task.status == TaskStatus.DELETED || task.status == TaskStatus.SKIPPED) return false
        val start = task.startDate ?: return false
        val end = task.endDate ?: start
        if (date.isBefore(start) || date.isAfter(end)) return false
        return start !in task.repeatRule.excludedDates
    }

    /** Only a persisted completion can be restored; future projections never can. */
    fun canRestore(task: Task): Boolean =
        task.status == TaskStatus.COMPLETED && !task.isProjection

    /**
     * Builds the next active occurrence. A finite totalCount includes the first occurrence.
     * The inclusive duration and reminder offset are retained.
     * When [notBefore] is set, missed rounds before that date are skipped so overdue daily
     * habits catch up to today instead of stacking one instance per missed day.
     */
    fun nextOccurrence(task: Task, notBefore: LocalDate? = null): Task? {
        var current = task
        repeat(520) {
            val next = advanceOccurrence(current) ?: return null
            val due = next.endDate ?: next.startDate ?: return next
            if (notBefore == null || !due.isBefore(notBefore)) return next
            current = next
        }
        return null
    }

    private fun advanceOccurrence(task: Task): Task? {
        val rule = task.repeatRule
        val start = task.startDate ?: return null
        if (rule.kind == RepeatKind.NONE) return null
        if (rule.totalCount != null && rule.occurrenceIndex >= rule.totalCount) return null

        val following = nextStart(start, rule)
        val dayShift = ChronoUnit.DAYS.between(start, following)
        val duration = task.endDate?.let { ChronoUnit.DAYS.between(start, it) } ?: 0
        val nextIndex = rule.occurrenceIndex + 1
        val rootSeriesId = task.seriesId ?: task.id
        return task.copy(
            id = "$rootSeriesId:$nextIndex",
            seriesId = rootSeriesId,
            startDate = following,
            endDate = following.plusDays(duration),
            reminderAt = task.reminderAt?.plusDays(dayShift),
            repeatRule = rule.copy(occurrenceIndex = nextIndex),
            status = TaskStatus.ACTIVE,
            isProjection = false
        )
    }

    /**
     * True when [date] falls on this occurrence or a later one generated by the repeat rule.
     * Completed / skipped / abandoned rows stay on their stored dates and never project.
     */
    fun occursOn(task: Task, date: LocalDate): Boolean {
        if (task.status == TaskStatus.DELETED || task.status == TaskStatus.SKIPPED) return false
        if (task.status != TaskStatus.ACTIVE) return isVisibleOn(task, date)
        return occurrenceStart(task, date) != null
    }

    fun isProjectedOccurrence(task: Task, date: LocalDate): Boolean =
        occursOn(task, date) && !isVisibleOn(task, date)

    /**
     * Stored round is always operable. An overdue repeating instance can also be completed
     * from a missed past projection. Today and future projections stay read-only until
     * the current round is handled.
     */
    fun canCompleteOn(task: Task, date: LocalDate, today: LocalDate): Boolean {
        if (task.isProjection) return false
        if (task.status == TaskStatus.DELETED || task.status == TaskStatus.SKIPPED) return false
        if (isVisibleOn(task, date)) return task.status == TaskStatus.ACTIVE || canRestore(task) ||
            task.status == TaskStatus.ABANDONED
        if (task.status != TaskStatus.ACTIVE) return false
        val due = task.endDate ?: task.startDate ?: return false
        return due.isBefore(today) && date.isBefore(today) && isProjectedOccurrence(task, date)
    }

    /** Start of the occurrence that covers [date], or null when that round is hidden or absent. */
    fun occurrenceStart(task: Task, date: LocalDate): LocalDate? {
        if (task.status == TaskStatus.DELETED) return null
        val start = task.startDate ?: return null
        val end = task.endDate ?: start
        val duration = ChronoUnit.DAYS.between(start, end).coerceAtLeast(0)
        val rule = task.repeatRule
        var cursor = start
        var index = rule.occurrenceIndex
        repeat(520) {
            if (rule.repeatUntil != null && cursor.isAfter(rule.repeatUntil)) return null
            val occurrenceEnd = cursor.plusDays(duration)
            val hidden = cursor in rule.excludedDates || (task.status == TaskStatus.SKIPPED && cursor == start)
            if (!hidden && !date.isBefore(cursor) && !date.isAfter(occurrenceEnd)) return cursor
            if (rule.kind == RepeatKind.NONE) return null
            if (rule.totalCount != null && index >= rule.totalCount) return null
            val next = nextStart(cursor, rule)
            if (!next.isAfter(cursor) || next.isAfter(date.plusDays(duration))) return null
            cursor = next
            index += 1
        }
        return null
    }

    /** Hide one round. Every other round of the same series stays. */
    fun excludingOccurrence(task: Task, date: LocalDate): Task {
        val occurrence = occurrenceStart(task, date) ?: date
        val rule = task.repeatRule
        return task.copy(repeatRule = rule.copy(excludedDates = rule.excludedDates + occurrence))
    }

    /**
     * Keep rounds that start before [date]. Null means [date] is the first stored round,
     * so the row itself has to be removed and earlier history rows stay untouched.
     */
    fun endingBefore(task: Task, date: LocalDate): Task? {
        val occurrence = occurrenceStart(task, date) ?: date
        val seriesStart = task.startDate ?: return null
        if (!occurrence.isAfter(seriesStart)) return null
        val until = occurrence.minusDays(1)
        val earlier = task.repeatRule.repeatUntil
        val cut = if (earlier != null && earlier.isBefore(until)) earlier else until
        return task.copy(repeatRule = task.repeatRule.copy(repeatUntil = cut))
    }

    fun isFutureOccurrence(task: Task, date: LocalDate, today: LocalDate): Boolean =
        !date.isBefore(today) && isProjectedOccurrence(task, date)

    /** Unscheduled tasks live in 收集箱 and stay off Today / Calendar. */
    fun isInbox(task: Task): Boolean {
        if (task.status == TaskStatus.DELETED || task.status == TaskStatus.SKIPPED) return false
        return task.startDate == null && task.endDate == null
    }

    fun inboxItems(tasks: List<Task>): List<Task> =
        tasks.filter(::isInbox).sortedWith(
            compareBy<Task> { it.status != TaskStatus.ACTIVE }.thenByDescending { it.updatedAt }
        )

    fun moveToInbox(task: Task): Task = task.copy(
        startDate = null,
        endDate = null,
        time = null,
        reminderAt = null,
        repeatRule = RepeatRule(),
        isProjection = false
    )

    private fun nextStart(start: LocalDate, rule: RepeatRule): LocalDate {
        var next = advance(start, rule)
        var guard = 0
        while (rule.skipHolidays && ChinaHolidays.isHoliday(next) && guard++ < 24) next = advance(next, rule)
        return next
    }

    private fun advance(start: LocalDate, rule: RepeatRule): LocalDate {
        val interval = rule.interval.coerceAtLeast(1).toLong()
        return when (rule.kind) {
            RepeatKind.NONE -> start
            RepeatKind.DAILY -> start.plusDays(interval)
            RepeatKind.WEEKDAYS -> nextWeekly(start, setOf(1, 2, 3, 4, 5), interval)
            RepeatKind.WEEKLY -> if (rule.weekdays.isEmpty()) start.plusWeeks(interval)
                else nextWeekly(start, rule.weekdays.filter { it in 1..7 }.toSet(), interval)
            RepeatKind.MONTHLY -> monthly(start, rule.monthDay ?: start.dayOfMonth, interval)
            RepeatKind.YEARLY -> {
                val shifted = start.plusYears(interval)
                monthly(shifted.minusMonths(1), rule.monthDay ?: start.dayOfMonth, 1)
            }
        }
    }

    private fun monthly(start: LocalDate, requestedDay: Int, interval: Long): LocalDate {
        val nextMonth = YearMonth.from(start).plusMonths(interval)
        return nextMonth.atDay(requestedDay.coerceIn(1, nextMonth.lengthOfMonth()))
    }

    private fun nextWeekly(from: LocalDate, allowedIsoDays: Set<Int>, intervalWeeks: Long): LocalDate {
        if (allowedIsoDays.isEmpty()) return from.plusWeeks(intervalWeeks)
        val origin = from.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))
        var candidate = from.plusDays(1)
        repeat(370) {
            val weeks = ChronoUnit.WEEKS.between(origin, candidate.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)))
            if (weeks % intervalWeeks == 0L && candidate.dayOfWeek.value in allowedIsoDays) return candidate
            candidate = candidate.plusDays(1)
        }
        return from.plusWeeks(intervalWeeks)
    }
}

/** Statutory rest days used by the repeat option “跳过法定节假日”. */
object ChinaHolidays {
    private val dates: Set<LocalDate> = buildSet {
        fun add(year: Int, month: Int, days: IntRange) = days.forEach { add(LocalDate.of(year, month, it)) }
        add(2026, 1, 1..1)
        add(2026, 2, 15..23)
        add(2026, 4, 4..6)
        add(2026, 5, 1..5)
        add(2026, 6, 19..21)
        add(2026, 9, 25..27)
        add(2026, 10, 1..7)
    }

    fun isHoliday(date: LocalDate): Boolean = date in dates

    fun festival(date: LocalDate): String? = when (date.monthValue to date.dayOfMonth) {
        1 to 1 -> "元旦"
        10 to 1 -> "国庆节"
        10 to 18 -> if (date.year == 2026) "重阳节" else null
        10 to 31 -> "万圣节"
        else -> null
    }
}
